### ISSUE TITLE
Publish `redmine_decision_tree` plugin:

### ISSUE THREAD

**Issue by dkastl** [gtt-project/redmine_decision_tree#4]
- [x] use branch `main`
- [x] has branch `develop`
- [ ] has tests (if not create issue)
- [ ] has CI with GH Actions (if not create issue)
- [x] has `LICENSE`
- [x] has `README.md`
- [x] comments are in English (if not create issue)

**Comment by sanak** [comment]
Close this, because I created the new issue (#5).
